{application,bunt,
             [{config_mtime,1748914682},
              {compile_env,[{bunt,[color_aliases],error}]},
              {optional_applications,[]},
              {applications,[kernel,stdlib,elixir]},
              {description,"256 color ANSI coloring in the terminal"},
              {modules,['Elixir.Bunt','Elixir.Bunt.ANSI',
                        'Elixir.Bunt.ANSI.Sequence']},
              {registered,[]},
              {vsn,"1.0.0"}]}.
