{application,mox,
             [{config_mtime,1748914682},
              {optional_applications,[]},
              {applications,[kernel,stdlib,elixir,logger,nimble_ownership]},
              {description,"Mocks and explicit contracts for Elixir"},
              {modules,['Elixir.Mox','Elixir.Mox.Application',
                        'Elixir.Mox.UnexpectedCallError',
                        'Elixir.Mox.VerificationError']},
              {registered,[]},
              {vsn,"1.2.0"},
              {mod,{'Elixir.Mox.Application',[]}}]}.
